# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python:
  - 3.5
  - 3.6
  - 3.7

# Install the codecov pip dependency
install:
  - pip install codecov pytest
  - pip install -r requirements.txt

# Run the unit test
script:
  - coverage run -m pytest ./tests/

# Push the results back to codecov
after_success:
  - codecov
